# Generated by Django 3.2.9 on 2021-11-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='joined',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
