# Generated by Django 3.2.9 on 2021-11-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_event_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='joined',
        ),
    ]
